name: Deploy

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
      - name: Display tag name
        run: echo ${{ steps.get_tag.outputs.TAG_NAME }}
