name: Deploy

on:
  push:
    tags:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{GITHUB_REF#refs/tags/}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Display the tag that triggered the workflow
        run: |
          echo "Tag that triggered the workflow: $TAG_NAME"