name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ GIT_REF#refs/tags/ }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Display the tag that triggered the workflow
        run: |
          echo "Tag: $TAG"
          echo "Tag that triggered the workflow: ${GITHUB_REF#refs/tags/}"