name: Release

on:
  push:
    branches:
      - main
  inputs:
    version:
      description: >
        Chhose version:
      required: true
      default: 'minor'
      options:
        patch:
          description: Bump version patch
          value: patch
        minor:
          description: Bump version minor
          value: minor
        major:
          description: Bump version major
          value: major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install bumpversion
         
      - name: Bump Version
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags
          current_version=$(git describe --tags --match 'v*' `git rev-list --tags --max-count=1` | sed 's/^v//')
          if [ -z "$current_version" ]
          then
            new_version=1.0.0
          else
            new_version=$(bumpversion --current-version $current_version ${{ inputs.version }}" --list | grep new_version= | sed 's/^new_version=//')
          fi
          git tag v$new_version

      - name: Push Tags
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tags: true