name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: >
          Choose version:
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: '${{ secrets.ACTIONS_USER }}'
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install bumpversion
         
      - name: Bump Version
        run: |
          git fetch --tags
          current_version=$(git tag -l "v*" | sort -V | tail -n1 | sed 's/^v//')
          if [ -z "$current_version" ]
          then
            new_version=1.0.0
          else
            new_version=$(bumpversion --current-version $current_version ${{ inputs.version }} --list | grep new_version= | sed 's/^new_version=//')
          fi
          git tag v$new_version

      - name: Push Tags
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.ACTIONS_USER }}'
          tags: true