name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install bumpversion

      - name: Set Git identity
        run: |
          git config --local user.email "josue.rosadeavila@gmail.com"
          git config --local user.name "josuerosadeavila"

      - name: Print Current Version
        run: |
          current_version=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $current_version
         
      - name: Bump Version
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: bumpversion --current-version {{ current_version }} minor

      - name: Print New Version
        run: echo {{ new_version }}

      - name: Create tag
        run: git tag v{{ new_version }}

      - name: Push Tags
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tags: true