name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install bumpversion

      - name: Set Git identity
        run: |
          git config --local user.email "josue.rosadeavila@gmail.com"
          git config --local user.name "josuerosadeavila"
         
      - name: Bump Version
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags
          current_version=$(git describe --tags --match 'v*' `git rev-list --tags --max-count=1` | sed 's/^v//')
          echo $current_version
          bumpversion --current-version $current_version minor
